---
- name: Jenkins CLI
  get_url:
    url: "http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path | default('') }}/jnlpJars/jenkins$
    dest: /tmp/jenkins-cli.jar
    owner: root
    group: root
    mode: 0444

- name: Scripts for Jenkins CLI
  template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    owner: root
    group: root
    mode: 0444
  with_items:
    - security_realm_name.sh
    - proxy_configuration.groovy
    - update_center_refresh.groovy

- name: Security Realm Checking
  shell: "bash /tmp/security_realm_name.sh"
  register: jenkins2_security_realm_name

- name: CLI Password File Creation
  copy:
    content: "{{ jenkins2_cli_password }}"
    dest: /tmp/jenkins-cli-password
    mode: 0400
  when: jenkins2_security_realm_name.stdout != "hudson.security.SecurityRealm$None"

- name: CLI Login
  shell: "java -jar /tmp/jenkins-cli.jar -s http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path$
  when: jenkins2_security_realm_name.stdout != "hudson.security.SecurityRealm$None"

- name: Proxy Configuration
  shell: "java -jar /tmp/jenkins-cli.jar -s http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path$

- name: Update Center Refresh
  shell: "java -jar /tmp/jenkins-cli.jar -s http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path$

- name: Plugins Installation
  shell: "java -jar /tmp/jenkins-cli.jar -s http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path$
  with_items:
    - "{{ jenkins2_suggested_plugins }}"
    - "{{ jenkins2_plugins }}"
  notify:
    - Restart Jenkins
- name: CLI Logout
  shell: "java -jar /tmp/jenkins-cli.jar -s http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path$
  when: jenkins2_security_realm_name.stdout != "hudson.security.SecurityRealm$None"

- name: CLI Password File Deletion
  file:
    path: /tmp/jenkins-cli-password
    state: absent

